### PR TITLE
Add soil temperature and soil moisture to ERA5 data, STEMMUS_SCOPE recipe

### LINKED ISSUE #47: Missing Registration for Soil Moisture Data in 'src/zampy/reference/variables.py'
Hello,

I noticed that in the file "src/zampy/reference/variables.py," there is no registration for Soil Temperature levels 1 to 4 and Volumetric Soil Water layers 1 to 4. These variables are needed to roundabout the model warm up problem. We have faced problems when downloading those data from ERA5 land using a command line recipe. And i feel this might be the problem. Does adding variables in that script enable us to download them? 

Best regards,
Prajwal

### PR DESCRIPTION
**Pull request by BSchilperoort**
To add these I had to merge them and add a "depth" dimension. The original files are split by layer...

Closes #47

Note that the CDS is slow, so running the recipe might take a while. Running it overnight is probably best.

Example recipe:
```yaml
# config (folder, login info etc goes to a ~/.zampy/config file)
name: "soil temperature test"

download:
  time: ["2019-01-01", "2019-01-31"]
  bbox: [54, 6, 53, 5] # NESW
  datasets:
    era5_land:
      variables:
        - soil_temperature
        - soil_moisture

convert:
  convention: ALMA
  frequency: 1H  # outputs at 1 hour frequency. Pandas-like freq-keyword.
  resolution: 0.25  # output resolution in degrees.
```

### CODE REVIEW

**Comment by BSchilperoort** [comment]
@SarahAlidoost you should be able to run the following recipe now, which will download all input data for STEMMUS_SCOPE for half a year.
To make this recipe work for longer time periods we'll have to add a feature that adds NaNs if the requested start/end time is not appropriate for a dataset.

```yaml
# config (folder, login info etc goes to a ~/.zampy/config file)
name: "STEMMUS_SCOPE_input"

download:
  time: ["2020-01-01", "2020-06-30"]
  bbox: [60, 10, 50, 0] # NESW
  datasets:
    era5_land:
      variables:
        - air_temperature
        - dewpoint_temperature
        - soil_temperature
        - soil_moisture
    era5:
      variables:
        - total_precipitation
        - surface_thermal_radiation_downwards
        - surface_solar_radiation_downwards
        - surface_pressure
        - eastward_component_of_wind
        - northward_component_of_wind
    eth_canopy_height:
      variables:
        - height_of_vegetation
    fapar_lai:
      variables:
        - leaf_area_index
    land_cover:
      variables:
        - land_cover
    prism_dem_90:
      variables:
        - elevation
    cams:
      variables:
        - co2_concentration

convert:
  convention: ALMA
  frequency: 1H  # outputs at 1 hour frequency. Pandas-like freq-keyword.
  resolution: 0.25  # output resolution in degrees.
```

**Comment by BSchilperoort** [comment]
Not sure why the Windows tests are failing. I am able to reproduce it on my machine, but it seems like the netCDF4 library or xarray is not releasing the file lock on the netCDF files. This makes the temp dir clean up fail because it cannot unlink the files.

I did not change that part of the code either, so it probably has something to do with a new version somewhere. Or with Dask because I did make the CI use Dask distributed (to avoid memory issues as the default scheduler is bad).

**Comment by SarahAlidoost** [comment]
> Not sure why the Windows tests are failing. I am able to reproduce it on my machine, but it seems like the netCDF4 library or xarray is not releasing the file lock on the netCDF files. This makes the temp dir clean up fail because it cannot unlink the files.
> 
> I did not change that part of the code either, so it probably has something to do with a new version somewhere. Or with Dask because I did make the CI use Dask distributed (to avoid memory issues as the default scheduler is bad).

Looking at [the log of action](https://productionresultssa17.blob.core.windows.net/actions-results/e81503d0-075a-44b2-ad1a-f7d97ee8c997/workflow-job-run-65a11588-9cd0-5baf-d5ae-cc0004f79c9f/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-19T15%3A09%3A06Z&sig=9jVmA9NgFFjVTTlZLZWaObuKHkw2ESUeReSOSnZl4B4%3D&ske=2024-07-20T02%3A00%3A14Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-19T14%3A00%3A14Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-07-19T14%3A59%3A01Z&sv=2023-11-03), it seems that there are different errors on windows: 

```
E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\a\\zampy\\zampy\\tests\\test_data\\fapar-lai\\tmp\\tmpvxggwz_9\\c3s_LAI_20190110000000_GLOBE_PROBAV_V3.0.1.nc'
```

```
E           NotADirectoryError: [WinError 267] The directory name is invalid: 'D:\\a\\zampy\\zampy\\tests\\test_data\\fapar-lai\\tmp\\tmpvxggwz_9\\c3s_LAI_20190110000000_GLOBE_PROBAV_V3.0.1.nc'
```

```
FAILED tests/test_datasets/test_fapar_lai.py::TestFaparLAI::test_ingest - NotADirectoryError: [WinError 267] The directory name is invalid: 'D:\\a\\zampy\\zampy\\tests\\test_data\\fapar-lai\\tmp\\tmpvxggwz_9\\c3s_LAI_20190110000000_GLOBE_PROBAV_V3.0.1.nc'
```

I think Dask workers cause these errors. Can you please refactor `dask.distributed.Client()` in `test_fapar_lai.py::TestFaparLAI::test_ingest` with `submit` and `result` methods of `client` and check if it fixes the errors.

**Review by SarahAlidoost — CHANGES_REQUESTED** [review]
@BSchilperoort thanks :+1: I am running the recipe `STEMMUS_SCOPE_input`. Downloading from CDS is not very fast. But the changes in this PR look good. Can you please add the recipe `STEMMUS_SCOPE_input` as a yaml file to a subfolder e.g. `recipes` in the root and also add it to the documentation. Also, see my comment about the `dask.distributed.Client()` in the test.

**Comment by BSchilperoort** [comment]
FAPAR dataset test fixed, now a different test fails with a segfault due to rasterio...

**Review by SarahAlidoost — APPROVED** [review]
@BSchilperoort well done, thanks.

**Pull request merged**
